import type { Metadata } from 'next';
// import localFont from 'next/font/local';
import { Lato } from 'next/font/google';
import './globals.css';
import { ChatPage, HomeLayout, LoadingSpinner } from '@/components';
import AuthProvider, { AuthConsumer } from '@/features/AuthenticationProvider';
import { getUser } from './actions';

import ChatPageSupportProvicer from '@/features/ChatPageSupportProvicer';
import dynamic from 'next/dynamic';

const Device = dynamic(() => import('@/features/DeviceProvider'), {
  ssr: false,
  loading: () => (
    <div className='w-full h-screen'>
      <LoadingSpinner />
    </div>
  ),
});

const defaultFonts = Lato({
  variable: '--font-family',
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  console.log(user);
  // fff8fb
  return (
    <html lang='en'>
      <body className={`${defaultFonts.className} antialiased bg-canvas-dark`}>
        <AuthProvider>
          <Device>
            {() => (
              <AuthConsumer
                loggedInChild={
                  <ChatPageSupportProvicer>
                    <ChatPage />
                  </ChatPageSupportProvicer>
                }
                unloggedInChild={<HomeLayout>{children}</HomeLayout>}
              />
            )}
          </Device>
        </AuthProvider>
      </body>
    </html>
  );
}
